-- ============================================================
-- CAPA CRUDA INMOGES (espejo de la API) — esquema SEPARADO del Streamlit
-- Esquema:  DB_ANALYTICS.SCH_CORE   (YA EXISTE, owner ACCOUNTADMIN;
--           NO SCH_PLD, para no revolver con las tablas del Streamlit)
-- IMPORTANTE: el rol de la ingesta ROLE_ANALYTICS puede CREATE TABLE aquí
--   (verificado), así que estas CREATE TABLE se pueden correr con ROLE_ANALYTICS
--   —NO se requiere ROLE_DEV ni CREATE SCHEMA—. El script las crea solo.
-- Cada tabla lleva RAW_JSON = registro original completo (red de NO-PÉRDIDA).
-- ============================================================
-- (Sin CREATE SCHEMA: SCH_CORE ya existe. Sin GRANT USAGE de esquema:
--  ROLE_ANALYTICS y ROLE_DASHBOARD ya lo tienen. GRANT SELECT a ROLE_DASHBOARD por
--  tabla se hace al crearlas, ver al final.)

-- ---------- EMPRESA ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_EMPRESA (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    ID_EMPRESA VARCHAR, ALIAS VARCHAR, RAZON_SOCIAL VARCHAR, RFC VARCHAR,
    TIPO_PERSONA VARCHAR, REGIMEN_SOCIETARIO VARCHAR, ESTATUS_MODULO VARCHAR,
    ID_EXTERNO VARCHAR, DOMICILIO_FISCAL_PRINCIPAL VARCHAR,
    DOMICILIO_FISCAL_JSON VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- INMUEBLE  (PLD: FOLIO, CUENTA_PREDIAL, CLAVE_CATASTRAL, CATASTRO, TIPO_INMUEBLE, domicilio) ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_INMUEBLE (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    ID_INMUEBLE VARCHAR, INMUEBLE VARCHAR,
    FOLIO VARCHAR, CUENTA_PREDIAL VARCHAR, CLAVE_CATASTRAL VARCHAR, CATASTRO VARCHAR,
    TIPO_INMUEBLE VARCHAR, ESTATUS VARCHAR,
    CALLE VARCHAR, NO_EXTERIOR VARCHAR, NO_INTERIOR VARCHAR, COLONIA VARCHAR,
    CODIGO_POSTAL VARCHAR, CIUDAD VARCHAR, ESTADO VARCHAR, PAIS VARCHAR, DIRECCION VARCHAR,
    MAPA VARCHAR, ZONA VARCHAR, REGION VARCHAR, PLAZA VARCHAR, MERCADO VARCHAR,
    SEGMENTO_NEGOCIO VARCHAR, CENTRO_COSTOS VARCHAR, DIMENSION_FINANCIERA VARCHAR, ADMINISTRADOR VARCHAR,
    PRECIO_M2_RENTA NUMBER(18,4), PRECIO_M2_MANTENIMIENTO NUMBER(18,4),
    M2_RENTABLES NUMBER(18,4), M2_CONSTRUCCION NUMBER(18,4), M2_TERRENO NUMBER(18,4),
    M2_ESTACIONAMIENTO NUMBER(18,4), CAJONES_ESTACIONAMIENTO VARCHAR,
    CONSTRUCCION VARCHAR, TERRENO VARCHAR, ADQUISICION NUMBER(18,2), FECHA_ADQUISICION VARCHAR,
    ID_EXTERNO VARCHAR, CREATED_DATE VARCHAR, MODIFIED_DATE VARCHAR,
    DOCUMENTOS_JSON VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- UNIDAD  (PLD: ID_UNIDAD, NO_INTERIOR; INMUEBLE_TXT = join débil por nombre) ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_UNIDAD (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    ID_UNIDAD VARCHAR, UNIDAD VARCHAR, INMUEBLE_TXT VARCHAR,
    USO VARCHAR, ESTATUS VARCHAR, CUENTA_PREDIAL VARCHAR, CLAVE_CATASTRAL VARCHAR,
    PRECIO_RENTA NUMBER(18,2), PRECIO_M2_RENTA NUMBER(18,4), PRECIO_MANTENIMIENTO NUMBER(18,2),
    PRECIO_DEPOSITO_GARANTIA NUMBER(18,2),
    CALLE VARCHAR, NO_EXTERIOR VARCHAR, NO_INTERIOR VARCHAR, COLONIA VARCHAR,
    CODIGO_POSTAL VARCHAR, CIUDAD VARCHAR, ESTADO VARCHAR, PAIS VARCHAR,
    M2_RENTABLES NUMBER(18,4), M2_CONSTRUCCION NUMBER(18,4), M2_TERRENO NUMBER(18,4),
    PISOS VARCHAR, HABITACIONES VARCHAR, BANOS_COMPLETOS VARCHAR, MEDIOS_BANOS VARCHAR,
    ANIOS_CONSTRUCCION VARCHAR, DESCRIPCION VARCHAR,
    CREATED_DATE VARCHAR, MODIFIED_DATE VARCHAR,
    DOCUMENTOS_JSON VARCHAR, PORTALES_JSON VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- CONTRATO (hub) — idempotente por EMPRESA ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_CONTRATO (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    EMPRESA VARCHAR,
    ID_CONTRATO VARCHAR, ARRENDATARIO VARCHAR,
    INMUEBLE VARCHAR, ID_INMUEBLE VARCHAR, UNIDAD VARCHAR, ID_UNIDAD VARCHAR,
    SUCURSAL VARCHAR, DOMICILIO_FISCAL VARCHAR, GIRO VARCHAR,
    ESTATUS VARCHAR, GRUPO_AVISO VARCHAR,
    FECHA_INICIAL VARCHAR, FECHA_FINAL VARCHAR, FECHA_FIRMA VARCHAR, FECHA_RENOVACION VARCHAR,
    FECHA_ENTREGA VARCHAR, FECHA_OPERACION VARCHAR, FECHA_CANCELACION VARCHAR,
    FRECUENCIA VARCHAR, MONEDA VARCHAR, TIPO_CAMBIO VARCHAR,
    SUBTOTAL NUMBER(18,2), DESCUENTO NUMBER(18,2), IVA NUMBER(18,2),
    RETENCION_IVA NUMBER(18,2), ISR NUMBER(18,2), TOTAL NUMBER(18,2),
    ID_EXTERNO VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- CONTRATO_CONCEPTO (hija) — PLD: TIPO_CONCEPTO aísla la Renta ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_CONTRATO_CONCEPTO (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    EMPRESA VARCHAR, ID_CONTRATO VARCHAR, ORDEN NUMBER,
    DESCRIPCION VARCHAR, TIPO_CONCEPTO VARCHAR,
    PRODUCTO_SERVICIO VARCHAR, UNIDAD_MEDIDA VARCHAR,
    VALOR_UNITARIO NUMBER(18,2), IMPUESTOS VARCHAR, CUENTA_CONTABLE VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- ARRENDATARIO ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_ARRENDATARIO (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    ID_ARRENDATARIO VARCHAR, RAZON_SOCIAL VARCHAR, ALIAS VARCHAR, RFC VARCHAR,
    TIPO_PERSONA VARCHAR, FECHA VARCHAR, MEDIO_CONTACTO VARCHAR, ESTATUS_MODULO VARCHAR,
    CONTACTO_PRINCIPAL VARCHAR, SUCURSAL_PRINCIPAL VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- ARRENDATARIO_CONTACTO (hija) — PLD: TELEFONO ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_ARRENDATARIO_CONTACTO (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    ID_ARRENDATARIO VARCHAR, ID_CONTACTO VARCHAR,
    NOMBRE VARCHAR, TELEFONO VARCHAR, CORREO VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- SUCURSAL_ARRENDATARIO — idempotente por EMPRESA ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_SUCURSAL_ARRENDATARIO (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    EMPRESA VARCHAR,
    ID_SUCURSAL VARCHAR, ID_ARRENDATARIO VARCHAR, RAZON_SOCIAL VARCHAR, RFC VARCHAR,
    ALIAS_ARRENDATARIO VARCHAR, ALIAS_SUCURSAL VARCHAR, REGIMEN_FISCAL VARCHAR,
    CORREOS_CFDI VARCHAR, USO_CFDI VARCHAR, FORMA_PAGO VARCHAR, METODO_PAGO VARCHAR,
    CUENTA_CONTABLE VARCHAR,
    CALLE VARCHAR, NO_EXTERIOR VARCHAR, NO_INTERIOR VARCHAR, COLONIA VARCHAR,
    CODIGO_POSTAL VARCHAR, CIUDAD VARCHAR, ESTADO VARCHAR,
    ID_EXTERNO_ARRENDATARIO VARCHAR, ID_EXTERNO_SUCURSAL VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- PROPIETARIO ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_PROPIETARIO (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    ID_PROPIETARIO VARCHAR, RAZON_SOCIAL VARCHAR, ALIAS VARCHAR, RFC VARCHAR,
    TIPO_PERSONA VARCHAR, REGIMEN_FISCAL VARCHAR, ESTATUS_MODULO VARCHAR,
    CALLE VARCHAR, NO_EXTERIOR VARCHAR, NO_INTERIOR VARCHAR, COLONIA VARCHAR,
    CODIGO_POSTAL VARCHAR, CIUDAD VARCHAR, ESTADO VARCHAR, PAIS VARCHAR, FECHA VARCHAR,
    RAW_JSON VARCHAR
);

-- ---------- PLD_ENTIDAD (unificada arrendatario+propietario) — CORAZÓN PLD ----------
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.INMOGES_PLD_ENTIDAD (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    ORIGEN VARCHAR,                         -- 'ARRENDATARIO' | 'PROPIETARIO'  (llave de recarga por origen)
    ID_PADRE VARCHAR, RFC_PADRE VARCHAR, RAZON_SOCIAL_PADRE VARCHAR, EMPRESA VARCHAR,
    ID_PLD_ENTIDAD VARCHAR, TIPO_PERSONA VARCHAR,
    PF_NOMBRE VARCHAR, PF_APELLIDO_PAT VARCHAR, PF_APELLIDO_MAT VARCHAR, PF_FECHA_NAC VARCHAR, PF_CURP VARCHAR,
    ACTIVIDAD_ECONOMICA VARCHAR, FECHA_CONSTITUCION VARCHAR, GIRO_MERCANTIL VARCHAR,
    RPM_NOMBRE VARCHAR, RPM_APELLIDO_PAT VARCHAR, RPM_APELLIDO_MAT VARCHAR,
    RPM_FECHA_NAC VARCHAR, RPM_RFC VARCHAR, RPM_CURP VARCHAR,
    CALLE VARCHAR, COLONIA VARCHAR, NO_EXTERIOR VARCHAR, NO_INTERIOR VARCHAR, PAIS VARCHAR,
    CLAVE VARCHAR, TELEFONO VARCHAR, CORREO VARCHAR,
    RAW_JSON VARCHAR
);

-- ============================================================
-- CATÁLOGOS PLD (seed estático desde las plantillas el portal de avisos UIF z1/z2; NO son de la API)
-- 2 columnas base + VALOR = 'clave-descripción' (formato que exige el aviso)
-- ============================================================
CREATE TABLE IF NOT EXISTS DB_ANALYTICS.SCH_CORE.PLD_CATALOGO (
    LOAD_TS TIMESTAMP_NTZ(9) DEFAULT CAST(CONVERT_TIMEZONE('America/Mexico_City', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
    CATALOGO VARCHAR,     -- 'CatPais' | 'CatGiroMercantil' | 'CatActividadEconomica' | 'CatTipoInmueble' | ...
    CLAVE VARCHAR,
    DESCRIPCION VARCHAR,
    VALOR VARCHAR         -- 'clave-descripción'
);

-- ---------- GRANTS por tabla a ROLE_DASHBOARD (best-effort; ROLE_ANALYTICS es dueño de las que crea) ----------
-- (El dashboard hoy NO consume estas tablas; se otorga por si acaso. Si alguna
--  falla por permisos, no bloquea la ingesta.)
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_EMPRESA               TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_INMUEBLE             TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_UNIDAD              TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_CONTRATO           TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_CONTRATO_CONCEPTO  TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_ARRENDATARIO       TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_ARRENDATARIO_CONTACTO TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_SUCURSAL_ARRENDATARIO TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_PROPIETARIO        TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.INMOGES_PLD_ENTIDAD        TO ROLE ROLE_DASHBOARD;
GRANT SELECT ON TABLE DB_ANALYTICS.SCH_CORE.PLD_CATALOGO             TO ROLE ROLE_DASHBOARD;

-- Nota: la tabla de BENEFICIARIO (captura manual, sin fuente API) va en SCH_PLD
-- junto a PLD_AVISO_FORM, con su propio DDL (fuera de este archivo).
