-- ============================================================================
--  ddl_sync_incremental.sql
--  Columnas de control para el SYNC INCREMENTAL (huella + soft-delete).
--  Se corre con el rol DUEÑO de SCH_CORE (ROLE_ANALYTICS).
--
--  ROW_HASH   = MD5 del contenido de negocio (RAW_JSON sin createdDate/modifiedDate).
--               Señal de cambio para el MERGE (si el hash difiere -> hubo cambio real).
--  ACTIVO     = TRUE por defecto; se pone FALSE (soft-delete) si el registro deja de
--               venir en un pull COMPLETO (nunca borrado físico).
--  FECHA_BAJA = cuándo se marcó inactivo.
--
--  ADD COLUMN IF NOT EXISTS -> re-ejecutable sin error.
-- ============================================================================

-- === ARRANQUE (prueba): solo CONTRATO ===
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_CONTRATO ADD COLUMN IF NOT EXISTS ROW_HASH   VARCHAR;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_CONTRATO ADD COLUMN IF NOT EXISTS ACTIVO     BOOLEAN DEFAULT TRUE;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_CONTRATO ADD COLUMN IF NOT EXISTS FECHA_BAJA TIMESTAMP_NTZ(9);

-- === RESTO DE ENTIDADES (correr al escalar, después de validar contratos) ===
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_INMUEBLE     ADD COLUMN IF NOT EXISTS ROW_HASH VARCHAR;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_INMUEBLE     ADD COLUMN IF NOT EXISTS ACTIVO BOOLEAN DEFAULT TRUE;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_INMUEBLE     ADD COLUMN IF NOT EXISTS FECHA_BAJA TIMESTAMP_NTZ(9);

ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_UNIDAD       ADD COLUMN IF NOT EXISTS ROW_HASH VARCHAR;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_UNIDAD       ADD COLUMN IF NOT EXISTS ACTIVO BOOLEAN DEFAULT TRUE;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_UNIDAD       ADD COLUMN IF NOT EXISTS FECHA_BAJA TIMESTAMP_NTZ(9);

ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_ARRENDATARIO ADD COLUMN IF NOT EXISTS ROW_HASH VARCHAR;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_ARRENDATARIO ADD COLUMN IF NOT EXISTS ACTIVO BOOLEAN DEFAULT TRUE;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_ARRENDATARIO ADD COLUMN IF NOT EXISTS FECHA_BAJA TIMESTAMP_NTZ(9);

ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_PROPIETARIO  ADD COLUMN IF NOT EXISTS ROW_HASH VARCHAR;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_PROPIETARIO  ADD COLUMN IF NOT EXISTS ACTIVO BOOLEAN DEFAULT TRUE;
ALTER TABLE DB_ANALYTICS.SCH_CORE.INMOGES_PROPIETARIO  ADD COLUMN IF NOT EXISTS FECHA_BAJA TIMESTAMP_NTZ(9);
